# Generated by Django 5.2.2 on 2025-06-12 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Eventos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=20)),
                ('identificacion', models.FileField(blank=True, null=True, upload_to='identificaciones/')),
                ('comentario', models.TextField(blank=True)),
                ('acepta_politicas', models.BooleanField(default=False)),
                ('desea_recibir_noticias', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='Eventos.evento')),
            ],
        ),
    ]
