# Generated by Django 5.2.2 on 2025-06-12 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('lugar', models.CharField(default='Lugar pendiente', max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos_imagenes/')),
            ],
        ),
    ]
